# This docker-compose file is only for development purposes

# TODO: add backend
services: 
  frontend:
    image: ghcr.io/nasz-elektryk/basedbook-frontend
    build: .
    network_mode: host
    ports:
      - "3000:5000"
    volumes:
      - .:/app
      - /app/node_modules
  backend:
    image: ghcr.io/nasz-elektryk/basedbook-backend
    network_mode: host
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: pnpm start:dev